# Generated by Django 5.2 on 2026-01-10 13:31

import rent.models.common_imports_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_remove_contract_base_rent_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.PositiveIntegerField(db_index=True, default=rent.models.common_imports_models.generate_contract_number, help_text='رقم العقد الفريد (يُولد تلقائياً)', unique=True, verbose_name='رقم العقد'),
        ),
    ]
