# Generated by Django 5.2 on 2026-01-23 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_alter_contractmodification_change_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodification',
            name='change_percentage',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='نسبة الزيادة (+) أو التخفيض (-) %', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة التغيير %'),
        ),
    ]
