# Generated by Django 6.0 on 2026-01-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_add_payment_proof_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-start_date', '-created_at'], 'permissions': [('activate_contract', 'تفعيل عقد'), ('terminate_contract', 'إنهاء عقد'), ('view_contract_statement', 'عرض كشف حساب العقد')], 'verbose_name': 'عقد', 'verbose_name_plural': 'العقود'},
        ),
        migrations.AlterModelOptions(
            name='contractmodification',
            options={'ordering': ['-effective_date', '-created_at'], 'permissions': [('apply_contractmodification', 'تطبيق تعديل عقد')], 'verbose_name': 'تعديل عقد', 'verbose_name_plural': 'تعديلات العقود'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-receipt_date', '-created_at'], 'permissions': [('post_receipt', 'ترحيل سند قبض'), ('cancel_receipt', 'إلغاء سند قبض'), ('print_receipt', 'طباعة سند قبض'), ('export_receipt_pdf', 'تصدير سند PDF')], 'verbose_name': 'سند قبض', 'verbose_name_plural': 'سندات القبض'},
        ),
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'ordering': ['name'], 'permissions': [('view_reports', 'عرض التقارير'), ('export_reports', 'تصدير التقارير')], 'verbose_name': 'قالب تقرير', 'verbose_name_plural': 'قوالب التقارير'},
        ),
    ]
