# Generated by Django 6.0.1 on 2026-02-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_alter_backup_id_alter_backupschedule_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodification',
            name='vat_input_type',
            field=models.CharField(blank=True, choices=[('percentage', 'نسبة من الإيجار'), ('fixed', 'مبلغ مقطوع')], default='percentage', help_text='اختر طريقة إدخال القيمة المضافة: نسبة أو مبلغ مقطوع', max_length=20, verbose_name='طريقة إدخال القيمة المضافة'),
        ),
        migrations.AlterField(
            model_name='contractmodification',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ القيمة المضافة (يُحسب تلقائياً أو يُدخل مباشرة)', max_digits=12, null=True, verbose_name='مبلغ القيمة المضافة'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('showroom', 'معرض'), ('workshop', 'ورشه'), ('ofiec', 'مكتب'), ('station', 'محطة محروقات'), ('atm', ' صراف الي سيار'), ('hall', 'صاله ')], db_index=True, default='showroom', help_text='الحالة الحالية للوحدة', max_length=20, verbose_name='نوع الوحده'),
        ),
    ]
