# Generated by Django 5.2 on 2026-01-03 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المستخدم')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('login_failed', 'محاولة دخول فاشلة'), ('access', 'دخول صفحة')], max_length=50, verbose_name='العملية')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن')),
                ('model_name', models.CharField(db_index=True, max_length=255, verbose_name='اسم الموديل')),
                ('object_repr', models.CharField(blank=True, max_length=500, null=True, verbose_name='تمثيل الكائن')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='القيم القديمة')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='القيم الجديدة')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='التغييرات فقط')),
                ('request_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='مسار الطلب')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='نوع الطلب')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='معلومات المتصفح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع المحتوى')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل التدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_audit_created'), models.Index(fields=['user', '-created_at'], name='idx_audit_user'), models.Index(fields=['action', '-created_at'], name='idx_audit_action'), models.Index(fields=['model_name', '-created_at'], name='idx_audit_model'), models.Index(fields=['ip_address'], name='idx_audit_ip')],
            },
        ),
    ]
